
import json
import logging
import os
import platform
import random
import sys
import aiosqlite

import discord
from discord import app_commands
from discord.ext import commands, tasks
from discord.ext.commands import Context
from discord_logging import add_discord_logging

from database import DatabaseManager
from datetime import datetime
from dotenv   import load_dotenv
from enum     import Enum

from bot_shared import *
from msf_shared import *

from rich.console import Console
from rich.traceback import Traceback
console = Console()


if not os.path.isfile(f"{os.path.realpath(os.path.dirname(__file__))}/tokens/discord_config.json"):
	sys.exit("'./tokens/discord_config.json' not found! Please add it and try again.")
else:
	with open(f"{os.path.realpath(os.path.dirname(__file__))}/tokens/discord_config.json") as file:
		config = json.load(file)

# Load environment variables
load_dotenv(override=True)

# Establish Discord intents
intents = discord.Intents.default()
intents.message_content = False



  #8888b. 88888888888     d8888 8888888b. 88888888888      888      .d88888b.   .d8888b.   .d8888b.  8888888 888b    888  .d8888b.  
#88P  Y88b    888        d88888 888   Y88b    888          888     d88P" "Y88b d88P  Y88b d88P  Y88b   888   8888b   888 d88P  Y88b 
#88b.         888       d88P888 888    888    888          888     888     888 888    888 888    888   888   88888b  888 888    888 
 #Y888b.      888      d88P 888 888   d88P    888          888     888     888 888        888          888   888Y88b 888 888        
    #Y88b.    888     d88P  888 8888888P"     888          888     888     888 888  88888 888  88888   888   888 Y88b888 888  88888 
      #888    888    d88P   888 888 T88b      888          888     888     888 888    888 888    888   888   888  Y88888 888    888 
#88b  d88P    888   d8888888888 888  T88b     888          888     Y88b. .d88P Y88b  d88P Y88b  d88P   888   888   Y8888 Y88b  d88P 
 #Y8888P"     888  d88P     888 888   T88b    888          88888888 "Y88888P"   "Y8888P88  "Y8888P88 8888888 888    Y888  "Y8888P88 



# Console Formatter
class LoggingFormatter(logging.Formatter):

	COLORS = {
		logging.DEBUG:    ansi.ltyel,
		logging.INFO:     ansi.ltblu,
		logging.WARNING:  ansi.ltyel,
		logging.ERROR:    ansi.red,
		logging.CRITICAL: ansi.ltred,
	}

	def format(self, record):
		format = "(dkgray){asctime}(reset) (log_color){levelname:<5}(reset) (green){name}(reset) {message}"

		format = format.replace("(log_color)", self.COLORS[record.levelno])

		format = format.replace("(dkgray)", ansi.dkgray)
		format = format.replace("(reset)",  ansi.rst)
		format = format.replace("(green)",  ansi.ltgrn)
		format = format.replace("(yellow)", ansi.ltyel)
		format = format.replace("(cyan)",   ansi.ltcyan)
		format = format.replace("(red)",    ansi.ltred)

		formatter = logging.Formatter(format, "%m-%d %H:%M:%S", style="{")
		return formatter.format(record)

# Start the logger
logger = logging.getLogger("RosterBot")
logger.setLevel(logging.INFO)
logging.addLevelName(logging.WARNING, "WARN")

# Create directories for logs and image output
log_dir = f'{msf2csv.get_local_path()}trace{os.sep}'
img_dir = f'{msf2csv.get_local_path()}reports{os.sep}'

# If they don't exist yet, make them
if not os.path.exists(log_dir):	os.makedirs(log_dir)
if not os.path.exists(img_dir):	os.makedirs(img_dir)

# Clean up old files in these directories
msf2csv.cleanup_old_files(log_dir)
msf2csv.cleanup_old_files(img_dir)

# Create console handler
console_handler = logging.StreamHandler()
console_handler.setFormatter(LoggingFormatter())

# Create file handler
launch_time    = datetime.now().strftime("%y.%m.%d-%H%M%S")
file_handler   = logging.FileHandler(filename=f"{log_dir}discord.{launch_time}.log", encoding="utf-8", mode="w")
file_formatter = logging.Formatter(
	"{asctime} {levelname:<5} {name}: {message}", "%m-%d %H:%M:%S", style="{"
)
file_handler.setFormatter(file_formatter)

# Add the default handlers
logger.addHandler(console_handler)
logger.addHandler(file_handler)

# Only setup Discord logging if we've defined a destination
if os.getenv('WEBHOOK_LOGGING_URL'):

	# Establish Discord logging, error message queue, and location of images generated by the bot
	add_discord_logging(logger, os.getenv('WEBHOOK_LOGGING_URL'), os.getenv('WEBHOOK_ERROR_URL'), file_dirs=[img_dir])



#888888b. 8888888 .d8888b.   .d8888b.   .d88888b.  8888888b.  8888888b.       888888b.    .d88888b. 88888888888 
#88  "Y88b  888  d88P  Y88b d88P  Y88b d88P" "Y88b 888   Y88b 888  "Y88b      888  "88b  d88P" "Y88b    888     
#88    888  888  Y88b.      888    888 888     888 888    888 888    888      888  .88P  888     888    888     
#88    888  888   "Y888b.   888        888     888 888   d88P 888    888      8888888K.  888     888    888     
#88    888  888      "Y88b. 888        888     888 8888888P"  888    888      888  "Y88b 888     888    888     
#88    888  888        "888 888    888 888     888 888 T88b   888    888      888    888 888     888    888     
#88  .d88P  888  Y88b  d88P Y88b  d88P Y88b. .d88P 888  T88b  888  .d88P      888   d88P Y88b. .d88P    888     
#888888P" 8888888 "Y8888P"   "Y8888P"   "Y88888P"  888   T88b 8888888P"       8888888P"   "Y88888P"     888     



class DiscordBot(commands.Bot):
	def __init__(self) -> None:
		super().__init__(
			command_prefix=[],
			intents=intents,
			help_command=None,
			owner_id = 564592015975645184,
			allowed_contexts = app_commands.AppCommandContext(guild=True, dm_channel=True, private_channel=True),
			allowed_installs = app_commands.AppInstallationType(guild=True, user=True),
		)
		"""
		This creates custom bot variables so that we can access these variables in cogs more easily.
		"""
		self.logger = logger
		self.config = config
		self.database = None
		self.failing = False
		self.bot = self
		
		# Give a pointer to the bot to the logger so logger can send owner error messages if requested
		for handler in logger.handlers:
			if type(handler).__name__ == 'GangedHandler':
				handler.target_handler.owner_id = self.owner_id



	async def init_db(self) -> None:
		async with aiosqlite.connect(
			f"{os.path.realpath(os.path.dirname(__file__))}/database/database.db"
		) as db:
			with open(
				f"{os.path.realpath(os.path.dirname(__file__))}/database/schema.sql"
			) as file:
				await db.executescript(file.read())
			await db.commit()



	async def load_cogs(self) -> None:
		"""
		The code in this function is executed whenever the bot will start.
		"""
		for file in os.listdir(f"{os.path.realpath(os.path.dirname(__file__))}/cogs"):
			if file.endswith(".py"):
				extension = file[:-3]
				try:
					await self.load_extension(f"cogs.{extension}")
					self.logger.info(f"Loaded extension '{ansi.white}{extension}{ansi.rst}'")
				except Exception as e:
					exception = f"{type(e).__name__}: {e}"
					self.logger.error(
						f"Failed to load extension {ansi.ltred}{extension}{ansi.rst}\n{ansi.white}{exception}{ansi.rst}"
					)



	# Update the bot status randomly
	@tasks.loop(minutes=5.0)
	async def status_task(self) -> None:
		statuses = ["with MSF!", "with rosters!", "with stats!", "with charts!"]
		await self.change_presence(activity=discord.Game(random.choice(statuses)))



	# Check driver_pool, kill and recreate any old drivers
	@tasks.loop(minutes=15.0)
	async def driver_pool_task(self) -> None:
		await check_driver_pool(self)



	# Nightly process to try to keep old AUTHs active longer.
	@tasks.loop(time=datetime.now().time().replace(7,0,0,0))   # Time in UTC. Midnight PST DST = (7,0,0,0)
	async def auth_refresh_task(self) -> None:
		await auto_auth_refresh(self)



	# Verify the MSF RosterBot is still online!
	@tasks.loop(seconds=5)
	async def stayalive_task(self) -> None:

		# Don't check for heartbeat if stayalive_disabled 
		if stayalive_disabled():
			return

		# Only allow check every 15s (every third try) if dev_mode_disabled or if failing
		if datetime.now().second % 9 if self.failing else 3 and dev_mode_disabled():
			return

		# Reset the flag
		self.failing = False

		for bot_name in {'MSFRosterBot', 'SigmaSupport'}:
			if not bot_is_running(bot_name):
				print (f'{ansi.red}WARNING!{ansi.rst} {ansi.white}{bot_name}{ansi.rst} was {ansi.under}NOT{ansi.rst} running...{ansi.ltyel}RELAUNCHED!{ansi.rst}')

				# Tripped!
				self.failing = True



	# Wait until bot ready before running tasks
	@status_task.before_loop
	@stayalive_task.before_loop
	@driver_pool_task.before_loop
	@auth_refresh_task.before_loop
	async def before_launch(self) -> None:
		await self.wait_until_ready()



	# Executed when the bot starts the first time
	async def setup_hook(self) -> None:
		self.logger.info(f"Logged in as {self.user.name}")
		self.logger.info(f"discord.py API version: {discord.__version__}")
		self.logger.info(f"Python version: {platform.python_version()}")
		self.logger.info(f"Running on: {platform.system()} {platform.release()} ({os.name})")
		self.logger.info("="*27)
		await self.init_db()
		await self.load_cogs()
		self.status_task.start()
		self.stayalive_task.start()
		self.driver_pool_task.start()
		self.auth_refresh_task.start()
		self.database = DatabaseManager(
			connection=await aiosqlite.connect(
				f"{os.path.realpath(os.path.dirname(__file__))}/database/database.db"
			)
		)

		# Update icon image for handler to match bot's own icon
		for handler in self.logger.handlers:
			if type(handler).__name__ == 'GangedHandler':
				handler.target_handler.avatar_url = self.user.avatar.url



	async def on_ready(self):
		"""
		This function is called when the bot successfully connects to Discord.
		"""
		# If we have no registered commands, we have not been globally synced
		if not await self.tree.fetch_commands():
			self.logger.info(f'No commands registered. Requesting a global sync.')
			synced = await self.tree.sync()
			if synced:
				self.logger.info(f'Success! Sync complete. {len(synced)} commands synced globally.')
				self.logger.info(f'Clients may need to be restarted to see correct integration.')
			else:
				self.logger.error(f'Sync FAILED! Please retry.')

		status_msg = f'{ansi.gray}Bot is{ansi.rst} {ansi.white}{str(bot.status).upper()}{ansi.rst} {ansi.gray}as{ansi.rst} {ansi.ltyel}{bot.user}{ansi.rst} {ansi.gray}(ID: {bot.user.id}){ansi.rst}'
		self.logger.info(f"{ansi.dkgray}COMMAND CLOSED:{ansi.rst} {ansi.ltblu}on_ready(){ansi.rst} {status_msg}")



	async def on_message(self, message: discord.Message) -> None:
		"""
		The code in this event is executed every time someone sends a message, with or without the prefix
		"""
	
		# Ignore MSF RosterBot messages and messages from other bots.
		if message.author == self.user or message.author.bot:
			return

		# Use this to generate the SIGMA Poster and SIGMA Openings graphics
		context = await self.get_context(message)

		await self.invoke(context)  # type: ignore



	async def on_command(self, context: Context):
		"""
		Report the command being called
		"""
		self.logger.info     (f'{ansi.white}COMMAND CALLED:{ansi.rst} {ansi.ltcyan}/{context.command.qualified_name}{ansi.rst}')

		channel = context.channel
		
		channel_type = 'thread' if 'thread' in channel.type.name else 'private' if 'private' in channel.type.name else 'group' if 'group' in channel.type.name else 'channel'
		channel_name = get_discord_channel_name(channel)
		
		# Report the User making the call
		user_app_int = f'(User App)' if context.interaction and context.interaction.is_user_integration() else ''
		self.logger.info (f"{ansi.white}{'By User:':>15} {ansi.rst}{context.author.id:<19} {ansi.ltyel}{context.author.name}{ansi.rst} {ansi.yellow}{user_app_int}{ansi.rst}")

		# Report server name if on a server
		if context.guild:
			guild_app_int = f'{ansi.green}(Using Bot)' if context.guild.name or not context.interaction else '(Guild App)' if context.interaction.is_guild_integration() else '(User App)'
			self.logger.info (f"{ansi.white}{'On Server:':>15} {ansi.rst}{context.guild.id:<19} {ansi.ltyel}{context.guild.name or 'Unknown Server'}{ansi.rst} {ansi.yellow}{guild_app_int}{ansi.rst}")
		# If in a DM with RosterBot
		elif 'group' not in channel_type and channel.recipient == bot.user:
			channel_name += f'{ansi.rst} {ansi.green}(with {bot.user}!)'

		self.logger.info (f"{ansi.white}{'In '+channel_type.title()+':':>15} {ansi.rst}{channel.id:<19} {ansi.ltyel}{channel_name}{ansi.rst}")

		# Dump the list of arguments
		for arg, value in context.kwargs.items():
			if isinstance(value, Enum):
				value = f'{value.name} {ansi.cyan}({value.value})'
			if value not in ('', None):
				self.logger.info (f'{arg:>14}: {ansi.ltyel if value else ansi.yellow}{value}{ansi.rst}')



	async def on_command_completion(self, context: Context) -> None:
		"""
		The code in this event is executed every time a normal command has been *successfully* executed.
		"""
		command_name = f'{ansi.ltblu}/{context.command.qualified_name}{ansi.rst}'
		user_name    = f'{ansi.yellow}{context.author}{ansi.rst}'
		channel_name = f'{ansi.yellow}{get_discord_channel_name(context.channel)}{ansi.rst}'

		channel_type = 'thread ' if 'thread' in context.channel.type.name else 'channel '
		
		self.logger.info(f"{ansi.dkgray}COMMAND CLOSED:{ansi.rst} {command_name} {ansi.gray}by{ansi.rst} {user_name} {ansi.gray}in {channel_type if context.guild else ''}{ansi.rst}{channel_name}")



	async def on_command_error(self, context: Context, error) -> None:
		"""
		The code in this event is executed every time a normal valid command catches an error.
		"""
		if isinstance(error, commands.CommandOnCooldown):
			minutes, seconds = divmod(error.retry_after, 60)
			hours, minutes = divmod(minutes, 60)
			hours = hours % 24
			embed = discord.Embed(
				description=f"**Please slow down** - You can use this command again in {f'{round(hours)} hours' if round(hours) > 0 else ''} {f'{round(minutes)} minutes' if round(minutes) > 0 else ''} {f'{round(seconds)} seconds' if round(seconds) > 0 else ''}.",
				color=0xE02B2B,
			)
			await context.send(embed=embed)
		elif isinstance(error, commands.NotOwner):
			embed = discord.Embed(
				description="You are not the owner of the bot!", color=0xE02B2B
			)
			await context.send(embed=embed)
			command_name = f'{ansi.ltblu}/{context.command.qualified_name}{ansi.rst}'
			if context.guild:
				self.logger.warning(
					f"{ansi.ltyel}{context.author}{ansi.rst} (ID: {context.author.id}) tried to execute {command_name} in the guild {ansi.ltyel}{context.guild.name or 'Unknown Server'}{ansi.rst} {ansi.white}(ID: {context.guild.id}){ansi.rst}, but is not the bot owner."
				)
			else:
				self.logger.warning(
					f"{ansi.ltyel}{context.author}{ansi.rst} (ID: {context.author.id}) tried to execute {command_name} command in {ansi.ltyel}{get_discord_channel_name(context.channel)}{ansi.rst}, but is not the bot owner."
				)
		elif isinstance(error, commands.MissingPermissions):
			embed = discord.Embed(
				description="You are missing the permission(s) `"
				+ ", ".join(error.missing_permissions)
				+ "` to execute this command!",
				color=0xE02B2B,
			)
			await context.send(embed=embed)
		elif isinstance(error, commands.BotMissingPermissions):
			embed = discord.Embed(
				description="I am missing the permission(s) `"
				+ ", ".join(error.missing_permissions)
				+ "` to fully perform this command!",
				color=0xE02B2B,
			)
			await context.send(embed=embed)
		elif isinstance(error, commands.MissingRequiredArgument):
			embed = discord.Embed(
				title="Error!",
				# We need to capitalize because the command arguments have no capital letter in the code and they are the first word in the error message.
				description=str(error).capitalize(),
				color=0xE02B2B,
			)
			await context.send(embed=embed)
		# Ignore invalid commands if not slash commands.
		elif isinstance(error, commands.CommandNotFound) and context.clean_prefix != '/':
			return
		else:
			# Extract the trackback stack
			stack = Traceback.extract(type(error), error, error.__traceback__, show_locals=False)

			# Get just the top stack
			stack.stacks = [stack.stacks[-1]]

			# Filter out frames we want to ignore
			frames = [frame for frame in stack.stacks[0].frames if frame.name not in ("_do_call", "run", "wrapped_func", "wrapped_func_async")]
			stack.stacks[0].frames = frames

			# Collect the formatted output
			with console.capture() as capture:
				console.print(Traceback(stack, show_locals=False))

			# Output the error information line by line
			error_msg = str(error)
			error_idx = error_msg.index(':')+1
			
			self.logger.error(f"{ansi.ltred}{error_msg[:error_idx]}{ansi.white}{error_msg[error_idx:]}!{ansi.rst}")
			for line in capture.get().split('\n'):
				self.logger.info(line)

		await self.on_command_completion(context)



bot = DiscordBot()
bot.run(os.getenv("TOKEN"))
